[2022-11-18T09:55:17.808+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:55:13.737196+00:00 [queued]>
[2022-11-18T09:55:17.874+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:55:13.737196+00:00 [queued]>
[2022-11-18T09:55:17.876+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T09:55:17.878+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T09:55:17.879+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T09:55:17.915+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): export_annotation> on 2022-11-18 09:55:13.737196+00:00
[2022-11-18T09:55:17.925+0000] {standard_task_runner.py:55} INFO - Started process 277 to run task
[2022-11-18T09:55:17.943+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DevDataOps', 'export_annotation', 'manual__2022-11-18T09:55:13.737196+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dev_data_ops.py', '--cfg-path', '/tmp/tmpt3x2xks3']
[2022-11-18T09:55:17.946+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask export_annotation
[2022-11-18T09:55:18.448+0000] {task_command.py:376} INFO - Running <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:55:13.737196+00:00 [running]> on host 517868cf30ca
[2022-11-18T09:55:19.029+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DevDataOps
AIRFLOW_CTX_TASK_ID=export_annotation
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T09:55:13.737196+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T09:55:13.737196+00:00
[2022-11-18T09:55:19.037+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-18T09:55:19.042+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --request GET http://127.0.0.1:3000/api/projects/2/export?exportType=CSV --header Authorization: Token 8823cc4fb910406253548fac3c458e495d6de86c --output annotations.csv']
[2022-11-18T09:55:19.086+0000] {subprocess.py:86} INFO - Output:
[2022-11-18T09:55:19.124+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:55:19.126+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:55:19.129+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2022-11-18T09:55:19.132+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused
[2022-11-18T09:55:19.171+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:55:19.181+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:55:19.185+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: Token
[2022-11-18T09:55:19.187+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:55:19.190+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:55:19.193+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 8823cc4fb910406253548fac3c458e495d6de86c
[2022-11-18T09:55:19.200+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2022-11-18T09:55:19.296+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-11-18T09:55:19.322+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=DevDataOps, task_id=export_annotation, execution_date=20221118T095513, start_date=20221118T095517, end_date=20221118T095519
[2022-11-18T09:55:19.401+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 33 for task export_annotation (Bash command failed. The command returned a non-zero exit code 6.; 277)
[2022-11-18T09:55:19.472+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T09:55:19.913+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
