[2022-11-18T09:13:52.544+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:13:49.829101+00:00 [queued]>
[2022-11-18T09:13:52.644+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:13:49.829101+00:00 [queued]>
[2022-11-18T09:13:52.647+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T09:13:52.649+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T09:13:52.651+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T09:13:52.742+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): export_annotation> on 2022-11-18 09:13:49.829101+00:00
[2022-11-18T09:13:52.791+0000] {standard_task_runner.py:55} INFO - Started process 3503 to run task
[2022-11-18T09:13:52.814+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DevDataOps', 'export_annotation', 'manual__2022-11-18T09:13:49.829101+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dev_data_ops.py', '--cfg-path', '/tmp/tmp_6anzvqn']
[2022-11-18T09:13:52.838+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask export_annotation
[2022-11-18T09:13:53.587+0000] {task_command.py:376} INFO - Running <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:13:49.829101+00:00 [running]> on host d470c2e62263
[2022-11-18T09:13:54.425+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DevDataOps
AIRFLOW_CTX_TASK_ID=export_annotation
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T09:13:49.829101+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T09:13:49.829101+00:00
[2022-11-18T09:13:54.440+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-18T09:13:54.455+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --request GET http://0.0.0.0:8080/api/projects/2/export?exportType=CSV --header Authorization: Token 8823cc4fb910406253548fac3c458e495d6de86c --output annotations.csv']
[2022-11-18T09:13:54.539+0000] {subprocess.py:86} INFO - Output:
[2022-11-18T09:13:54.566+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:13:54.570+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:13:54.574+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2022-11-18T09:13:54.576+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to 0.0.0.0 port 8080: Connection refused
[2022-11-18T09:13:54.578+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:13:54.588+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:13:54.620+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: Token
[2022-11-18T09:13:54.622+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:13:54.624+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:13:54.653+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 8823cc4fb910406253548fac3c458e495d6de86c
[2022-11-18T09:13:54.660+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2022-11-18T09:13:54.685+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-11-18T09:13:54.700+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=DevDataOps, task_id=export_annotation, execution_date=20221118T091349, start_date=20221118T091352, end_date=20221118T091354
[2022-11-18T09:13:54.726+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 27 for task export_annotation (Bash command failed. The command returned a non-zero exit code 6.; 3503)
[2022-11-18T09:13:54.791+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T09:13:54.859+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
