[2022-11-18T08:44:48.460+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T08:44:45.223829+00:00 [queued]>
[2022-11-18T08:44:48.495+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T08:44:45.223829+00:00 [queued]>
[2022-11-18T08:44:48.496+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T08:44:48.500+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T08:44:48.502+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T08:44:48.551+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): export_annotation> on 2022-11-18 08:44:45.223829+00:00
[2022-11-18T08:44:48.571+0000] {standard_task_runner.py:55} INFO - Started process 2372 to run task
[2022-11-18T08:44:48.629+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DevDataOps', 'export_annotation', 'manual__2022-11-18T08:44:45.223829+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dev_data_ops.py', '--cfg-path', '/tmp/tmpeuhonenj']
[2022-11-18T08:44:48.634+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask export_annotation
[2022-11-18T08:44:48.839+0000] {task_command.py:376} INFO - Running <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T08:44:45.223829+00:00 [running]> on host d470c2e62263
[2022-11-18T08:44:49.074+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DevDataOps
AIRFLOW_CTX_TASK_ID=export_annotation
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T08:44:45.223829+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T08:44:45.223829+00:00
[2022-11-18T08:44:49.078+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-18T08:44:49.082+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "curl \t\n        --request GET 'http://localhost:8081/api/projects/2/export?exportType=CSV' \t \n        --header 'Authorization: Token 8823cc4fb910406253548fac3c458e495d6de86c' \t \n        --output 'annotations.csv'"]
[2022-11-18T08:44:49.118+0000] {subprocess.py:86} INFO - Output:
[2022-11-18T08:44:49.144+0000] {subprocess.py:93} INFO - curl: try 'curl --help' or 'curl --manual' for more information
[2022-11-18T08:44:49.148+0000] {subprocess.py:93} INFO - /bin/bash: line 2: --request: command not found
[2022-11-18T08:44:49.150+0000] {subprocess.py:93} INFO - /bin/bash: line 3: --header: command not found
[2022-11-18T08:44:49.153+0000] {subprocess.py:93} INFO - /bin/bash: line 4: --output: command not found
[2022-11-18T08:44:49.157+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-11-18T08:44:49.195+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-18T08:44:49.207+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=DevDataOps, task_id=export_annotation, execution_date=20221118T084445, start_date=20221118T084448, end_date=20221118T084449
[2022-11-18T08:44:49.246+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task export_annotation (Bash command failed. The command returned a non-zero exit code 127.; 2372)
[2022-11-18T08:44:49.282+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T08:44:49.368+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
