[2022-11-18T09:09:42.855+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:09:40.158006+00:00 [queued]>
[2022-11-18T09:09:42.912+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:09:40.158006+00:00 [queued]>
[2022-11-18T09:09:42.914+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T09:09:42.916+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T09:09:42.917+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T09:09:42.972+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): export_annotation> on 2022-11-18 09:09:40.158006+00:00
[2022-11-18T09:09:42.995+0000] {standard_task_runner.py:55} INFO - Started process 3341 to run task
[2022-11-18T09:09:43.028+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DevDataOps', 'export_annotation', 'manual__2022-11-18T09:09:40.158006+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dev_data_ops.py', '--cfg-path', '/tmp/tmpyz5s3rr7']
[2022-11-18T09:09:43.030+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask export_annotation
[2022-11-18T09:09:43.278+0000] {task_command.py:376} INFO - Running <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:09:40.158006+00:00 [running]> on host d470c2e62263
[2022-11-18T09:09:43.405+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DevDataOps
AIRFLOW_CTX_TASK_ID=export_annotation
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T09:09:40.158006+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T09:09:40.158006+00:00
[2022-11-18T09:09:43.412+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-18T09:09:43.415+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --request GET http://127.0.0.1:8081/api/projects/2/export?exportType=CSV --header Authorization: Token 8823cc4fb910406253548fac3c458e495d6de86c --output annotations.csv']
[2022-11-18T09:09:43.442+0000] {subprocess.py:86} INFO - Output:
[2022-11-18T09:09:43.460+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:09:43.462+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:09:43.465+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2022-11-18T09:09:43.489+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to 127.0.0.1 port 8081: Connection refused
[2022-11-18T09:09:43.500+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:09:43.505+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:09:43.508+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: Token
[2022-11-18T09:09:43.509+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:09:43.511+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:09:43.513+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 8823cc4fb910406253548fac3c458e495d6de86c
[2022-11-18T09:09:43.515+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2022-11-18T09:09:43.536+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-11-18T09:09:43.546+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=DevDataOps, task_id=export_annotation, execution_date=20221118T090940, start_date=20221118T090942, end_date=20221118T090943
[2022-11-18T09:09:43.566+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task export_annotation (Bash command failed. The command returned a non-zero exit code 6.; 3341)
[2022-11-18T09:09:43.620+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T09:09:43.672+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
