[2022-11-18T08:47:39.916+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T08:47:35.381809+00:00 [queued]>
[2022-11-18T08:47:40.045+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T08:47:35.381809+00:00 [queued]>
[2022-11-18T08:47:40.047+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T08:47:40.050+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T08:47:40.052+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T08:47:40.216+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): export_annotation> on 2022-11-18 08:47:35.381809+00:00
[2022-11-18T08:47:40.246+0000] {standard_task_runner.py:55} INFO - Started process 2489 to run task
[2022-11-18T08:47:40.311+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DevDataOps', 'export_annotation', 'manual__2022-11-18T08:47:35.381809+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dev_data_ops.py', '--cfg-path', '/tmp/tmpyz20z5gd']
[2022-11-18T08:47:40.317+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask export_annotation
[2022-11-18T08:47:40.900+0000] {task_command.py:376} INFO - Running <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T08:47:35.381809+00:00 [running]> on host d470c2e62263
[2022-11-18T08:47:41.566+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DevDataOps
AIRFLOW_CTX_TASK_ID=export_annotation
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T08:47:35.381809+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T08:47:35.381809+00:00
[2022-11-18T08:47:41.674+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-18T08:47:41.685+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --request GET http://localhost:8081/api/projects/2/export?exportType=CSV --header Authorization: Token 8823cc4fb910406253548fac3c458e495d6de86c --output annotations.csv']
[2022-11-18T08:47:41.774+0000] {subprocess.py:86} INFO - Output:
[2022-11-18T08:47:41.846+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T08:47:41.852+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T08:47:41.858+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2022-11-18T08:47:41.859+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to localhost port 8081: Connection refused
[2022-11-18T08:47:41.860+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T08:47:41.870+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T08:47:41.929+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: Token
[2022-11-18T08:47:41.933+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T08:47:41.939+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T08:47:41.979+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 8823cc4fb910406253548fac3c458e495d6de86c
[2022-11-18T08:47:41.983+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2022-11-18T08:47:42.068+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-11-18T08:47:42.113+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=DevDataOps, task_id=export_annotation, execution_date=20221118T084735, start_date=20221118T084739, end_date=20221118T084742
[2022-11-18T08:47:42.236+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task export_annotation (Bash command failed. The command returned a non-zero exit code 6.; 2489)
[2022-11-18T08:47:42.328+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T08:47:42.423+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
