[2022-11-18T09:12:39.102+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:12:35.786853+00:00 [queued]>
[2022-11-18T09:12:39.133+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:12:35.786853+00:00 [queued]>
[2022-11-18T09:12:39.135+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T09:12:39.138+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T09:12:39.140+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T09:12:39.177+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): export_annotation> on 2022-11-18 09:12:35.786853+00:00
[2022-11-18T09:12:39.192+0000] {standard_task_runner.py:55} INFO - Started process 3454 to run task
[2022-11-18T09:12:39.211+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DevDataOps', 'export_annotation', 'manual__2022-11-18T09:12:35.786853+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dev_data_ops.py', '--cfg-path', '/tmp/tmpwqnnom9d']
[2022-11-18T09:12:39.213+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask export_annotation
[2022-11-18T09:12:39.475+0000] {task_command.py:376} INFO - Running <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T09:12:35.786853+00:00 [running]> on host d470c2e62263
[2022-11-18T09:12:39.815+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DevDataOps
AIRFLOW_CTX_TASK_ID=export_annotation
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T09:12:35.786853+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T09:12:35.786853+00:00
[2022-11-18T09:12:39.869+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-18T09:12:39.878+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --request GET http://0.0.0.0:8081/api/projects/2/export?exportType=CSV --header Authorization: Token 8823cc4fb910406253548fac3c458e495d6de86c --output annotations.csv']
[2022-11-18T09:12:39.928+0000] {subprocess.py:86} INFO - Output:
[2022-11-18T09:12:39.954+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:12:39.959+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:12:39.965+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2022-11-18T09:12:39.969+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to 0.0.0.0 port 8081: Connection refused
[2022-11-18T09:12:39.971+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:12:39.976+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:12:39.989+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: Token
[2022-11-18T09:12:39.994+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T09:12:40.003+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T09:12:40.046+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 8823cc4fb910406253548fac3c458e495d6de86c
[2022-11-18T09:12:40.061+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2022-11-18T09:12:40.138+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-11-18T09:12:40.157+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=DevDataOps, task_id=export_annotation, execution_date=20221118T091235, start_date=20221118T091239, end_date=20221118T091240
[2022-11-18T09:12:40.216+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task export_annotation (Bash command failed. The command returned a non-zero exit code 6.; 3454)
[2022-11-18T09:12:40.257+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T09:12:40.353+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
