[2022-11-18T08:51:52.889+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T08:51:50.274385+00:00 [queued]>
[2022-11-18T08:51:52.975+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T08:51:50.274385+00:00 [queued]>
[2022-11-18T08:51:52.977+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T08:51:52.985+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T08:51:52.986+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T08:51:53.049+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): export_annotation> on 2022-11-18 08:51:50.274385+00:00
[2022-11-18T08:51:53.060+0000] {standard_task_runner.py:55} INFO - Started process 2648 to run task
[2022-11-18T08:51:53.082+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DevDataOps', 'export_annotation', 'manual__2022-11-18T08:51:50.274385+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dev_data_ops.py', '--cfg-path', '/tmp/tmpalxygclq']
[2022-11-18T08:51:53.100+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask export_annotation
[2022-11-18T08:51:54.254+0000] {task_command.py:376} INFO - Running <TaskInstance: DevDataOps.export_annotation manual__2022-11-18T08:51:50.274385+00:00 [running]> on host d470c2e62263
[2022-11-18T08:51:54.541+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DevDataOps
AIRFLOW_CTX_TASK_ID=export_annotation
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T08:51:50.274385+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T08:51:50.274385+00:00
[2022-11-18T08:51:54.547+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-18T08:51:54.553+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --request GET http://localhost:8081/api/projects/2/export?exportType=CSV --header Authorization: Token 8823cc4fb910406253548fac3c458e495d6de86c --output annotations.csv']
[2022-11-18T08:51:54.587+0000] {subprocess.py:86} INFO - Output:
[2022-11-18T08:51:54.614+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T08:51:54.619+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T08:51:54.621+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2022-11-18T08:51:54.623+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to localhost port 8081: Connection refused
[2022-11-18T08:51:54.625+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T08:51:54.629+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T08:51:54.680+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: Token
[2022-11-18T08:51:54.684+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-11-18T08:51:54.690+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-11-18T08:51:54.711+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 8823cc4fb910406253548fac3c458e495d6de86c
[2022-11-18T08:51:54.718+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2022-11-18T08:51:54.753+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-11-18T08:51:54.767+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=DevDataOps, task_id=export_annotation, execution_date=20221118T085150, start_date=20221118T085152, end_date=20221118T085154
[2022-11-18T08:51:54.808+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 22 for task export_annotation (Bash command failed. The command returned a non-zero exit code 6.; 2648)
[2022-11-18T08:51:54.862+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T08:51:54.929+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
